"""Add approved_at to User

Revision ID: 412f133023c7
Revises: 
Create Date: 2025-08-22 14:49:49.169429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412f133023c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
